# Generated by Django 5.1.1 on 2024-10-04 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0002_alter_customer_address_alter_customer_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateField()),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("equipment_description", models.CharField(max_length=255)),
                ("os_version", models.CharField(max_length=255)),
                ("admin_password", models.CharField(blank=True, max_length=255)),
                ("customer_po", models.CharField(blank=True, max_length=255)),
                ("description_of_work", models.TextField()),
                ("work_performed", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
