# Generated by Django 5.1.1 on 2024-10-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_address_order_city_order_email_order_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="state",
        ),
        migrations.RemoveField(
            model_name="order",
            name="zip",
        ),
    ]
