# Generated by Django 5.1.1 on 2024-10-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_address_remove_order_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_number_prefix", models.CharField(blank=True, max_length=255)),
                ("order_number_suffix", models.CharField(blank=True, max_length=255)),
                ("order_number_next", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Order Configuration",
                "verbose_name_plural": "Order Configurations",
            },
        ),
    ]
