# Generated by Django 5.1.1 on 2024-10-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderconfig",
            name="order_number_suffix",
        ),
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
