# Generated by Django 5.1.1 on 2024-10-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_orderconfig_order_number_suffix_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
