# Generated by Django 5.1.1 on 2024-10-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_laboritem_orderlineitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="laboritem",
            name="default_labor_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="laboritem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="laboritem",
            name="labor_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
