# Generated by Django 5.1.1 on 2024-10-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_laboritem_default_labor_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderlineitem",
            name="rate",
        ),
    ]
