# Generated by Django 5.1.1 on 2024-10-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_remove_orderlineitem_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderlineitem",
            old_name="item",
            new_name="labor_item",
        ),
    ]
