# Generated by Django 5.1.1 on 2024-10-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_rename_item_orderlineitem_labor_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlineitem",
            name="date",
            field=models.DateField(),
        ),
    ]
