# Generated by Django 5.1.1 on 2024-10-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_alter_orderlineitem_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlineitem",
            name="labor_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
