# Generated by Django 5.1.1 on 2024-10-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_orderlineitem_labor_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlineitem",
            name="finish_time",
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="orderlineitem",
            name="labor_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=18
            ),
        ),
        migrations.AlterField(
            model_name="orderlineitem",
            name="start_time",
            field=models.TimeField(blank=True),
        ),
    ]
