# Generated by Django 5.1.1 on 2024-10-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_alter_orderlineitem_finish_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlineitem",
            name="finish_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderlineitem",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
